spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 358232262999549
            clientSecret: 618aa2f5b4ffb2cb9e81b8b87c32ef76
            scope:
              - email
              - public_profile