spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 543886023742149
            clientSecret: 4bf59bbbaf44796f464f6b49a75e1a36
            scope:
              - email
              - public_profile